### ISSUE TITLE
How long does it takes to synthesize text?

### ISSUE THREAD

**Issue by ishansan38** [chrisdonahue/wavegan#14]
Hi @chrisdonahue Great work on the repo! I was wondering how long does it takes to synthesize the text today, and if there are plans to improve the inference time. Thanks!

**Comment by chrisdonahue** [comment]
It takes only a few seconds to synthesize an hour of audio in batch mode (100ish one-second examples at a time) on a GPU. There are currently no plans to improve this (it is already many orders of magnitude faster than other audio synthesis neural networks), although it should naturally get faster with improved GPU hardware.

Thx for your interest.
