### ISSUE TITLE
tfrecord file cannot create

### ISSUE THREAD

**Issue by yuuSiVo** [chrisdonahue/wavegan#16]
Hi! This is yuu.

I'm trying wavegan to learning voice samples. But can't create tfrecord file in make_tfrecord.py

![image](https://user-images.githubusercontent.com/26115406/50203077-aee05200-03a3-11e9-8496-cc2804e769ab.png)

Like this.
What can I do?
plz help me

**Comment by SahajRana** [comment]
In this,


`python data/make_tfrecord.py \
	/my/audio/folder/trainset \
	./data/customdataset \
	--ext mp3 \
	--fs 16000 \
	--nshards 64 \
	--slice_len 1.5 \
`


either you have taken the wrong extension of audio file like `--ext mp3 \` in place of `--ext wav \`

or length of audio files is less than given length ie 1.5 sec `--slice_len 1.5 \`

**Comment by wbwdhr** [comment]
1.Try not to use Windows system. Make sure your system is Ubantu 16.04.
2. Make sure you have installed ffmpeg;
3.【--slice_len 1】The meaning of this command is the length of time per slice. So make sure that this length is less than the audio length of your dataset. eg：SC09 dateset length is about 1.2s，so you should set 【--slice_len】 to a value shorter than 1.2 seconds. If you set 【--slice_len】 to 1.5, you will get some empty files.
4. Check your Python version. If your Python version is Python 3，you may encounter some errors when you adjust the length of the slice before running it.
Like this：TypeError: 'S' has type str, but expected one of: bytes'
The solutions to this problem are listed below in issue: [Dataset creation problem #4] @LiangqunLu question. @chrisdonahue has offered a solution.

**Comment by chrisdonahue** [comment]
I just released an updated version of the codebase which no longer requires data preprocessing. Now you can just pass in a folder of MP3s/WAVs/OGGs/etc. during training.
