### ISSUE TITLE
Generate sound of more than 1 second as output

### ISSUE THREAD

**Issue by SahajRana** [chrisdonahue/wavegan#21]
Hello @chrisdonahue, this is a really amazing library as well as an implementation of gan for audios.
I've been successful in generating piano sounds with the dataset and model provided but the output is of 1 second. Could we increase this time? Please let me know. Thanks!

**Comment by chrisdonahue** [comment]
Thanks for your interest! I am currently preparing a v2 version of WaveGAN which will hopefully solve a lot of peoples' issues. Should be ready within a couple weeks.

**Comment by chrisdonahue** [comment]
I just merged v2. See the updated README for more information. Thanks again for your interest!

**Comment by SahajRana** [comment]
Thanks a lot for such a fast response, I will give it a shot this week and will let you know how it goes!

**Comment by chrisdonahue** [comment]
Please do let me know about your experience with the new codebase. Especially let me know if you encounter any issues.
