### ISSUE TITLE
parameters 

### ISSUE THREAD

**Issue by pankajbadatia** [chrisdonahue/wavegan#24]
Hi i am working on a audio 'wav'  file which is 44100Hz.   Can you please suggest me other settings needed to update. 
I have only two classes . I have made dataset dir and put wav files in it 

firstly i changed sample rate = 44100hz works with  --data_slice_len =16384  which is default I think.
tensorboard shows output . training starts scalars and other things are visible

also tried to change --data_slice_len = 32768  or 65536  (its ok if output file is not exactly 1sec , it can be more)
But tensorboard doesn't show output. no scalars and only graph and projector options available 

Can anyone help me on this . Its urgent..

**Comment by chrisdonahue** [comment]
this might be happening because your wav files are too short. Try adding command line arg `--data_pad_end`. You might also want to add `--data_first_slice`  which will only use the first "slice" from your waveforms, which I'm guessing you will want because you're using short waveforms.

**Comment by pankajbadatia** [comment]
all wav files are  1 sec each with sampling rate at 44100Hz
