### ISSUE TITLE
after shuffle buffer filled, the training seems stopped

### ISSUE THREAD

**Issue by Panshangka** [chrisdonahue/wavegan#26]
I train the wavegan model  using a single 1080Ti Nvidia Graphic card, 12 GB memory, After the screen shows shuffle buffer filled, the training seems stopped. It just stuck there for more than forty hours.

**Comment by pankajbadatia** [comment]
Its not stopped. check your gpu utilization.  
(1) tensorboard --logdir=./train            
use this for  looking the training steps in tensorboard.
(2) Incase the length of  wav file is not (16384, 32768, or 65536)  use --data_first_slice  and --data_pad_end as a true flag while training .

**Comment by pankajbadatia** [comment]
close this issue incase your problems has solved.
