### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by physhik** [chrisdonahue/wavegan#3]
Hi Chris, 

I have checked the beautiful generation of piano sound using wavegan model based on your tfrecord piano. BTW, in the code of colab, you miswrote the name of the tensor. 'G_z_spec:0' should be modified into 'global_step:0'. 

- Namshik

**Comment by chrisdonahue** [comment]
Closing this for now. Feel free to reopen and clarify the issue

**Comment by physhik** [comment]
Hi sorry for late comment. Was a bit busy. I could not find "G_z_spec:0" in any file. The tensorial multiplication is not matching. I also tried to test tfrecord file from custom data and your uploaded voice wav files but it did not work. Are you sure if you git push all the codes?

**Comment by polisen** [comment]
Hey, I too encountered this problem and I'm not sure how to solve it. I understand that this is one of those "go figure it out" situations but I've tried and would love some general pointers on how to resolve this. The error I get is G_z_spec:0 cannot be found.

**Comment by chrisdonahue** [comment]
The `G_z_spec:0` tensor is used to create a preview spectrogram for visualization purposes. The reason it is not found in the default metagraph from WaveGAN is that it requires parameters representing the average spectrogram from a particular dataset, which the WaveGAN script does not know by default (I manually added them to create the colab). You shouldn't need this tensor unless you really want to look at spectrograms for your generated waveforms. If you just want to hear the generated waveforms, use `G_z:0` instead.

**Comment by polisen** [comment]
Thanks - I tried it and of course it worked.
