### ISSUE TITLE
Question) Using reflection padding for Phase Shuffle???

### ISSUE THREAD

**Issue by soohyun123** [chrisdonahue/wavegan#30]
Hi, I'm an undergrad student, and recently I've been studying your paper and code: ADVERSARIAL AUDIO SYNTHESIS. 

I leave this issue thread out of curiosity about your implementation of the function **apply_phaseshuffle**(x, rad, pad_type='reflect').

so, you used 'reflect' mode for **tf.pad** function,

which means, for example, for an original array [1 2 3 4 5 6 7],

it results in [4 3 2 1 2 3 4 5 6 7] for phase = 3  ==> pad_l = 3, pad_r = 0.

Then we crop only the part [4 3 2 1 2 3 4] the final result of phase suffling.

At this point, these are my questions:

**First, is my understanding of your phase suffling correct??**

If it is correct, I guess it means we totally lose some data, 5 6 7, of the original array....

**Does this not make any problem????** T-T

**Comment by chrisdonahue** [comment]
Hi there.

Yes, your understanding of phase shuffle is correct. Some data is lost. This can be thought of as a regularization strategy, similar to dropout (which also loses data). Although, only the data at the edges is lost, and most of the center is preserved.
