### ISSUE TITLE
Error in training SpecGAN

### ISSUE THREAD

**Issue by saraalemadi** [chrisdonahue/wavegan#32]
I am facing the following error when training the specGAN on SC09 dataset:

Traceback (most recent call last):
  File "wavegan/train_specgan.py", line 750, in <module>
    moments(fps, args)
  File "wavegan/train_specgan.py", line 607, in moments
    _X_lmags = np.concatenate(_X_lmags, axis=0)
ValueError: need at least one array to concatenate

Any tips on how it can resolved?

**Comment by chrisdonahue** [comment]
Please see: https://github.com/chrisdonahue/wavegan/issues/28
