### ISSUE TITLE
v2 code could not train

### ISSUE THREAD

**Issue by yumath** [chrisdonahue/wavegan#34]
I only can run the v1 code, v2 code would be stuck when training Discriminator.

**Comment by chrisdonahue** [comment]
You need to provide more information

**Comment by yumath** [comment]
In the same environment, tensorflow-1.12 and Nvidia GTX 1080 Ti.
with the same dataset, sc09
v1:tf_records(path:data/sc09/all tf_records files) 
vs v2:raw WAV files(path:data/sc09/train/all raw WAV files)
v1 is trainable
When I started training v2, it runs a long time and nothing output. So I used a print function during training v2, print every time before training Discriminator. However, the print function would only be executed one time. And the program still be running, I waited for 10 hours and the program did not print again.

**Comment by ExtraLime** [comment]
Hi yumath did you find a fix for this issue? I seem to be having the same problem.

**Comment by yumath** [comment]
> Hi yumath did you find a fix for this issue? I seem to be having the same problem.

I have not solved this problem yet. And I think it may be a problem with data loading because the two versions of the model code are basically the same.

**Comment by ExtraLime** [comment]
Ok ill look into that. let you know if i can find anything.

**Comment by yumath** [comment]
Thanks a lot!

**Comment by chrisdonahue** [comment]
Even during successful training, nothing will print out of the console. Please use `tensorboard` to monitor the log directory and let me know if anything appears there.

**Comment by yumath** [comment]
> Even during successful training, nothing will print out of the console. Please use `tensorboard` to monitor the log directory and let me know if anything appears there.

When training v2, I used Tensorboard, but it only displays "Graph" and "Project", cannot see "Scalar" or "Histogram" and "Audio".

**Comment by ExtraLime** [comment]
I also am able to initialize the training and view it on tensorboard, however data never is written to the event logs after that.

**Comment by yumath** [comment]
> yumath, this was my error. In order to train the SC09 data, I reread the instructions, should add '--data_first_slice' for this dataset.

thank you! I tried it and really works.

**Comment by amjltc295** [comment]
I had the same problem and fixed it by adding `--data_first_slice`.  Without `--data_first_slice` the tensorboard just shows "Graph" and "Project" without any error messages. I think it would be nice to raise an error if the model is not reading data correctly.

**Comment by chrisdonahue** [comment]
I agree that it would be nice to error out in this case. I'm not entirely sure how to do that unfortunately. The file I/O is handled within the Tensorflow graph so it's nontrivial. Feel free to make a PR if you can figure it out :)
