### ISSUE TITLE
Generate a preview while training

### ISSUE THREAD

**Issue by spagliarini** [chrisdonahue/wavegan#38]
Hi, 
This might be more a tensorflow related question. I know that it is already possible to generate a preview while training (just having the two modalities at the same time). For reasons related to the framework (=server) where I am working I'm trying to integrate the preview into the train but I'm facing some difficulties. This might be due to how is defined the training section. If I actually try to generate a preview each time it trains the generator it complains (and it's right indeed the checkpoints are saved based on time - every #seconds). So I'm trying to modify the training (or add some option to do that), did you already did this? 
Thanks

**Comment by chrisdonahue** [comment]
Sorry for the delay. What does the error say when you try to run the preview script? I am not sure that the preview is all that useful TBH. It mostly just shows you generated results for the same latent code throughout training. Other than the latent code being fixed, it should be equal to the audio summaries from the training script which can be viewed in tensorboard. If you are using the postprocessing filters, the preview script also shows you the impulse response of the filter as an image, but this was mostly for debugging purposes.

**Comment by spagliarini** [comment]
You're right, my reason to have the preview integrated in the train modality is just to check the training. Anyway, I am not using the postprocessing filters but I'll get a look. Thanks.

**Comment by chrisdonahue** [comment]
Cool hopefully the training script is already outputting all of the information you need. Closing this for now, feel free to reopen!
