### ISSUE TITLE
What are G_z/audio/0 and x/audio/0 generated in TensorBoard-Audio

### ISSUE THREAD

**Issue by saraalemadi** [chrisdonahue/wavegan#39]
Hi Chris,

I was wondering what are the  G_z/audio/0 and x/audio/0  audio clips generated in TensorBoard Audio tab. I have been looking for what they stand for but haven't found any information on that.

Thanks,
Sara

**Comment by chrisdonahue** [comment]
They are samples from the current training batch for the generated and real audio respectively

**Comment by saraalemadi** [comment]
Thanks for the info @chrisdonahue
