### ISSUE TITLE
Utilizing multiple GPU:s

### ISSUE THREAD

**Issue by polisen** [chrisdonahue/wavegan#41]
Hey - 

I currently hold a big AWS EC2-instance with multiple GPU:s. My biggest workflow-bottleneck whilst experimenting with this is training time and since I should be able to 8x it I was just wondering if you know what the biggest hurdle would be to implement it to run on multiple GPU:s. Cheers.

**Comment by chrisdonahue** [comment]
The hurdle is that you would need to split up the mini batches across the 8 GPUs, run the computation, then merge their gradient updates. Here is an official example if you want to give it a shot:

https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py
