### ISSUE TITLE
Batch training

### ISSUE THREAD

**Issue by toriving** [chrisdonahue/wavegan#45]
HI, @chrisdonahue 

I am trying to apply my sound file on Wavegan, your code.
However, I don't know this code has a batch training block.
In train_wavegan.py, I can find ' x = loader.decode_extract_and_batch(...)'
It is return dataset iterator and, x is called only once.
In my opinion, this means that batch size represents the total number of training data sets.
I expected the same code below, but could not find it.

```
dataset = tf.data.Dataset(...)
dataset = dataset.batch(batch_size)
iterator = dataset.make_one_shot_iterator()

x = iterator.get_next()

while True:
    try:
        print(sess.run(x), end=' ')  
    except tf.errors.OutOfRangeError: 
        print('end\n')
        break
```

Thanks.

**Comment by chrisdonahue** [comment]
Sorry, I am not sure I understand your question. The loader is only called once because it creates a tensorflow Graph which streams training examples from disc every time the iterator tensors are used. Does this answer your question?

**Comment by toriving** [comment]
> Sorry, I am not sure I understand your question. The loader is only called once because it creates a tensorflow Graph which streams training examples from disc every time the iterator tensors are used. Does this answer your question?

Oh, I understand it.
Thanks.
