### ISSUE TITLE
the new Generation code 

### ISSUE THREAD

**Issue by shin777kk** [chrisdonahue/wavegan#49]
Hi @chrisdonahue,

I used the v2 version of the trained model. 

Follow the Generation program in Read me and find that there is an error.

The error content is 
"The name 'z:0' refers to a Tensor which does not exist. The operation, 'z', does not exist in the graph."

What do I need to modify in "z = graph.get_tensor_by_name('z:0')"?

Please tell me the answer,  thank you.

**Comment by chrisdonahue** [comment]
Make sure you are loading the `infer.meta` MetaGraph from the training directory. There should be an operation called `z` in that Graph. Does this fix it?

**Comment by shin777kk** [comment]
thx
