### ISSUE TITLE
Raw Piano Files

### ISSUE THREAD

**Issue by ogugugugugua** [chrisdonahue/wavegan#5]
Dear chrisdonahue,
Hi! Your work wavegan was quite impressive and gave me a lot of inspirations to explore something more beyond this model. But as I tried to rebuild your model from scratch using pytorch according to your paper, something seemed to be wrong with my model, therefore I would like to ask if you are able to provide the raw file of the piano training data, so that I could verify if the training method of my model is wrong.
Really appreciate a lot if you could do me a favor! Thanks in advance!

**Comment by chrisdonahue** [comment]
Thank you for your interest! I am quite happy to provide the original WAV files. I have updated the README with the [link](http://deepyeti.ucsd.edu/cdonahue/mancini_piano.tar.gz)
