### ISSUE TITLE
Samplerate questions

### ISSUE THREAD

**Issue by SilvanMertes** [chrisdonahue/wavegan#53]
Hi!
I have a little question concerning the train-data that can be used.
As I see, the default sample rate that is used by WaveGan is 16k. Does this imply that I also have to convert the training data to 16k sample rate? The BachPiano pieces for example have a sample rate of 44.1k 
Thank you for your reply!

**Comment by go-dustin** [comment]
I don't know for sure but I don't think you do. I believe you use this to set the sample rate of the source  --data_sample_rate 44100

**Comment by chrisdonahue** [comment]
The script will automatically convert the sample rates of the source audio files into whatever sample rate you specify for the training script. The only exception is if you user `--data_fast_wav` to load files faster, in which case the file sample rate needs to match the specified sample rate to the training script.
