### ISSUE TITLE
Sample of D_loss and G_loss Tensorflow Graphs

### ISSUE THREAD

**Issue by saraalemadi** [chrisdonahue/wavegan#56]
Hi @chrisdonahue, 

Can you kindly share the D_loss and G_loss Tensorflow graphs at the end of your WaveGAN training of your experiment which you have mentioned in your paper given that I would like to verify my experiment outcomes against yours.

Thanks in advance

**Comment by chrisdonahue** [comment]
Sure. These are typical results for a successful run:

https://i.imgur.com/mKMvFaJ.png

**Comment by chrisdonahue** [comment]
It can vary a bit by dataset though. The first one is for birds, this one is drum soudn effects: https://i.imgur.com/Bexalaj.png

**Comment by saraalemadi** [comment]
Thanks a lot @chrisdonahue. Do you happen to have the output graphs for the Piano experiment as well? They will be very beneficial for me since the dataset I am working has closer characteristics to it.
