### ISSUE TITLE
About the stopping criteri you mentioned in other issues

### ISSUE THREAD

**Issue by bywbilly** [chrisdonahue/wavegan#61]
Hi,

Thanks for your excellent work. I am trying to train the model, however, I found you didn't implement the early stop (inception score). Can you explain a little bit about that? Like how many samples should I use to implement the inception score?

Thanks!

**Comment by chrisdonahue** [comment]
Thanks! I did actually implement early stopping on Inception score. You can see the relevant line here: https://github.com/chrisdonahue/wavegan/blob/master/train_wavegan.py#L500

Does this answer your questions?

**Comment by bywbilly** [comment]
> Thanks! I did actually implement early stopping on Inception score. You can see the relevant line here: https://github.com/chrisdonahue/wavegan/blob/master/train_wavegan.py#L500
> 
> Does this answer your questions?

Yes, this helps a lot. I used V1 previously since the reading bug of V2 and I noticed that you fixed the V2 bug. Also a little typo in the Inference part, you should import numpy. 

Thanks again!
