### ISSUE TITLE
What is the meaning of "phase" in this context ?

### ISSUE THREAD

**Issue by ahmed-fau** [chrisdonahue/wavegan#7]
Hi,

I have read the paper as well as the implementation of your interesting  WaveGan. However, I still don't know what the term "phase" refers to when you introduce the idea of phase shuffling.

According to the implementation of function _apply_phaseshuffle_ , I think the input signal x is padded with random number _rad_ along the sequence dimension. Then the signal is sliced to have length of _x_len_ .

What is the relation between this operation and the "phase" to be named as "phase shuffling" ? And how does this reduce the up-sampling artifacts ? 

I have implemented the whole network except this utility and my generated signals still have obvious background noise (I am training with part of sc09-data to generate the word "three" only and currently reached epoch number 1500) ... could this background noise decreased after adding the phase shuffling or this is irrelevant to up-sampling artifacts.

Thanks in advance

**Comment by chrisdonahue** [comment]
In this context, I am using *phase* to refer to the [incidental phase of the waveform](https://en.wikipedia.org/wiki/Phase_(waves)). The intuition is that the discriminator should give approximately the same answer for any waveform that has been shifted left or right by a few audio samples. Accordingly, we randomly shift the waveforms from both the real data and generator in the discriminator. This prevents the discriminator from learning a trivial policy
