### ISSUE TITLE
About TIMIT dataset

### ISSUE THREAD

**Issue by fancoo** [chrisdonahue/wavegan#8]
How do you preprocessing the TIMIT dataset ? Still by cutting them into 1 second each piece ? I notice that audio in TIMIT dataset are length of 1-2 seconds, if the audio length is 1.2s, you cut them each 1 second, them the second utterance contains only 0.2s, is that proper ?

**Comment by chrisdonahue** [comment]
I take ~1.5 second chunks from each audio file, then during training I randomly take 1 second from each of those chunks. This is a way of making sure each example always occurs at a random phase alignment. Using incomplete examples from the end of the file was an arbitrary decision. I don't think it should affect training too much. You can always override the `pad_end` option to be False [(relevant line of code)](https://github.com/chrisdonahue/wavegan/blob/master/data/make_tfrecord.py#L70)
