### ISSUE TITLE
Standardized threshold for cat activation?

### ISSUE THREAD

**Issue by Tylersuard** [chrisdonahue/wavegan#80]
Hello.  Toward the end of your paper on WaveGAN, you provide the most important metric of the paper: comparison of cat activation between different models.  I was wondering if there is a standardized scale one can use to determine if one's cat has been activated?
Thank you for your time.

**Comment by julianmcauley** [comment]
Hi Tyler, I am very sad to report that Lemonade has passed. As such this specific metric is no longer reproducible. As for how to measure cat activation in general, pupil radius is probably a decent proxy, but for the most part, cat activation is something you just know when you see.

**Comment by Tylersuard** [comment]
Hi Julian, I am sorry to hear about Lemonade's passing.  It might be a comfort to know that her life's work has made an impact in the AI world: as of right now the WAVEGAN paper is cited by 65 other papers on Google Scholar.
