### ISSUE TITLE
Error on Generation Colab notebook

### ISSUE THREAD

**Issue by Tylersuard** [chrisdonahue/wavegan#84]
KeyErrorTraceback (most recent call last)

<ipython-input-9-9877bf194eae> in <module>()
     11 
     12 # Generate
---> 13 z = graph.get_tensor_by_name('z:0')
     14 G_z = graph.get_tensor_by_name('G_z:0')[:, :, 0]
     15 G_z_spec = graph.get_tensor_by_name('G_z_spec:0')

2 frames

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   3836           raise KeyError("The name %s refers to a Tensor which does not "
   3837                          "exist. The operation, %s, does not exist in the "
-> 3838                          "graph." % (repr(name), repr(op_name)))
   3839         try:
   3840           return op.outputs[out_n]

KeyError: "The name 'z:0' refers to a Tensor which does not exist. The operation, 'z', does not exist in the graph."

**Comment by Tylersuard** [comment]
I'm not able to get this notebook up and running.  The tensorflow version you recommend (1.12) is incompatible with Colab's version of CUDA (9.0).

**Comment by Tylersuard** [comment]
I'm really interested in getting this to work, and I spent 8 hours training a model, is there anything you can do to fix this problem?

**Comment by xyz010** [comment]
Hello,

I think that the solution to this is to get the whole tensor by

`G_z = graph.get_tensor_by_name('G_z:0')`

instead of 

`G_z = graph.get_tensor_by_name('G_z:0')[:, :, 0]`

**Comment by Tylersuard** [comment]
@xyz010 Thank you!
