### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by Varshithpolu** [chrisdonahue/wavegan#9]
Hi
I am having trouble training with my data
I  sucessfully created tfrecord file
![screenshot from 2018-07-04 22 46 30](https://user-images.githubusercontent.com/25304603/42289358-97714dd6-7fdc-11e8-979a-eb04e0303258.png)

but when i use this data to train the GAN it has this problem

![screenshot from 2018-07-02 10-51-11](https://user-images.githubusercontent.com/25304603/42289455-3bd4a350-7fdd-11e8-8ac6-62d4407daf0b.png)

**Comment by chrisdonahue** [comment]
Generally this error arises when your training directory is wrong or the tfrecords are actually empty files. Check your command line argument for the directory of your tfrecords. If the directory is correct, try previewing one: `python data/preview_tfrecord.py examples-00-of-64.tfrecord ./`

**Comment by andimarafioti** [comment]
I had the same issue and in my case, I was using the actual tf.record file as the input instead of the folder where the files are. 
This is ok:
`python3 data/preview_tfrecord.py ./data/piano/train-0-of-8.tfrecord ./`
This gives the error described in this issue:
`python3 train_wavegan.py train ./train --data_dir data/piano/train-0-of-8.tfrecord`
This is ok:
`python3 train_wavegan.py train ./train --data_dir data/piano`

Hope this helps.

Btw, why are you creating several tf.records instead of a big one?

**Comment by spagliarini** [comment]
I am facing the same problem with a dataset I created, how did you solve this? 

I don't think it's empty my file because I had that issue and I solved it installing ffmpeg (as suggested in some issue here). And I'm using the folder not he actual file. 

Thanks for the help.

**Comment by chrisdonahue** [comment]
If you are facing this issue still, I would strongly recommend pulling in the latest v2 update that we just released. This allows you to train a WaveGAN directly on a folder from MP3s/WAVs/OGGs/etc. Requires librosa (for MP3s/OGGs) or scipy (for WAVs).

**Comment by spagliarini** [comment]
Hi! 
Thanks for the advice and sorry for the inconvenience. I'm downladed the updated version an tried to start the training using python 3.6 without gpu. It starts so I assume I can read successfully the dataset directly from WAVs. 

Then I tried with gpu using python 3.6 

This is the error I obtain:
dataset = tf.data.Dataset.from_tensor_slices(fps)
AttributeError: module 'tensorflow' has no attribute 'data'

**Comment by chrisdonahue** [comment]
I'm not sure. It sounds like you might not have the latest version of TF installed. Try pip install --upgrade tensorflow-gpu. Otherwise I would Google around for that specific error because it doesn't seem related to the WaveGAN code itself.
